import {
  FileText,
  Download,
  Eye,
  CalendarDays,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

function ReportCard({
  reportId = "RPT-204",
  title = "AI Investigation Summary",
  generatedBy = "Forensic AI System",
  date = "18 Aug 2026",
  status = "Verified",
  pages = 14,
}) {

  return (

    <div
      className="
        group
        relative
        overflow-hidden

        rounded-[38px]

        bg-white/30
        backdrop-blur-2xl

        border border-black/5

        p-7

        shadow-[0_20px_60px_rgba(15,23,42,0.06)]

        transition-all duration-500

        hover:-translate-y-1
        hover:shadow-[0_25px_70px_rgba(127,29,29,0.08)]
      "
    >

      {/* PAPER TEXTURE */}
      <div
        className="
          absolute inset-0

          opacity-[0.02]

          pointer-events-none

          bg-[radial-gradient(circle_at_center,#000_1px,transparent_1px)]

          bg-[length:22px_22px]
        "
      />

      {/* AMBIENT GLOW */}
      <div
        className="
          absolute
          top-0
          right-0

          w-56
          h-56

          rounded-full

          bg-red-500/10

          blur-3xl
        "
      />

      {/* RED STRING */}
      <div
        className="
          absolute

          top-10
          right-10

          w-28
          h-[2px]

          bg-gradient-to-r
          from-transparent
          via-red-700
          to-transparent

          rotate-[18deg]

          opacity-0

          group-hover:opacity-40

          transition-all duration-500

          shadow-[0_0_14px_rgba(127,29,29,0.4)]
        "
      />

      {/* TOP */}
      <div
        className="
          relative z-10

          flex
          items-start
          justify-between

          gap-5

          mb-8
        "
      >

        {/* LEFT */}
        <div className="flex items-start gap-5">

          {/* ICON */}
          <div
            className="
              relative

              w-16
              h-16

              rounded-[24px]

              bg-red-900/5

              border border-red-900/10

              flex
              items-center
              justify-center

              shadow-[0_0_30px_rgba(127,29,29,0.08)]

              shrink-0
            "
          >

            {/* GLOW */}
            <div
              className="
                absolute
                inset-0

                rounded-[24px]

                bg-red-500/10

                blur-xl
              "
            />

            <FileText
              size={28}
              className="
                relative z-10

                text-red-800
              "
            />
          </div>

          {/* CONTENT */}
          <div>

            {/* BADGE */}
            <div
              className="
                inline-flex
                items-center
                gap-2

                px-3
                py-1.5

                rounded-full

                bg-red-900/5
                border border-red-900/10

                text-[10px]
                font-black

                tracking-[2px]

                text-red-800

                mb-4
              "
            >

              <Sparkles size={10} />

              {reportId}
            </div>

            {/* TITLE */}
            <h2
              className="
                text-2xl
                font-black

                text-slate-900

                leading-snug
              "
            >
              {title}
            </h2>

            {/* GENERATED BY */}
            <p
              className="
                text-slate-500

                text-sm

                mt-3

                leading-6
              "
            >
              Generated by{" "}
              <span className="font-semibold text-slate-700">
                {generatedBy}
              </span>
            </p>
          </div>
        </div>

        {/* STATUS */}
        <div
          className="
            inline-flex
            items-center
            gap-2

            px-4
            py-2.5

            rounded-full

            bg-emerald-500/10

            border border-emerald-500/20

            text-emerald-700
            text-[11px]
            font-black

            tracking-[1.5px]

            uppercase

            shrink-0
          "
        >

          <div
            className="
              w-2
              h-2

              rounded-full

              bg-emerald-500

              animate-pulse
            "
          />

          {status}
        </div>
      </div>

      {/* DETAILS */}
      <div
        className="
          relative z-10

          space-y-5

          mb-8
        "
      >

        {/* DATE */}
        <div
          className="
            flex
            items-center
            gap-4

            text-sm
            text-slate-500
          "
        >

          <div
            className="
              w-11
              h-11

              rounded-2xl

              bg-red-900/5

              border border-red-900/10

              flex
              items-center
              justify-center
            "
          >

            <CalendarDays
              size={16}
              className="text-red-700"
            />
          </div>

          <span className="font-medium">
            {date}
          </span>
        </div>

        {/* PAGES */}
        <div
          className="
            flex
            items-center
            gap-4

            text-sm
            text-slate-500
          "
        >

          <div
            className="
              w-11
              h-11

              rounded-2xl

              bg-red-900/5

              border border-red-900/10

              flex
              items-center
              justify-center
            "
          >

            <ShieldCheck
              size={16}
              className="text-red-700"
            />
          </div>

          <span className="font-medium">
            {pages} Pages
          </span>
        </div>
      </div>

      {/* SUMMARY */}
      <div
        className="
          relative z-10

          overflow-hidden

          rounded-[28px]

          bg-white/40
          backdrop-blur-xl

          border border-black/5

          p-6

          shadow-[0_10px_30px_rgba(15,23,42,0.04)]

          mb-8
        "
      >

        {/* INNER GLOW */}
        <div
          className="
            absolute
            top-0
            right-0

            w-36
            h-36

            rounded-full

            bg-red-500/5

            blur-3xl
          "
        />

        <p
          className="
            relative z-10

            text-slate-500

            text-sm

            leading-8
          "
        >
          AI-generated forensic report containing
          autopsy analysis, evidence correlation,
          digital intelligence mapping, timeline
          reconstruction, behavioral profiling,
          and anomaly detection insights.
        </p>
      </div>

      {/* FOOTER */}
      <div
        className="
          relative z-10

          flex
          items-center

          gap-4
        "
      >

        {/* VIEW */}
        <button
          className="
            group/view

            relative
            overflow-hidden

            flex-1

            flex
            items-center
            justify-center

            gap-2.5

            px-5
            py-4

            rounded-[22px]

            bg-gradient-to-r
            from-red-900
            via-red-700
            to-red-900

            text-white
            font-bold

            shadow-[0_10px_30px_rgba(127,29,29,0.25)]

            transition-all duration-500

            hover:scale-[1.02]
          "
        >

          {/* SHINE */}
          <div
            className="
              absolute
              inset-0

              bg-gradient-to-r
              from-transparent
              via-white/10
              to-transparent

              translate-x-[-100%]

              group-hover/view:translate-x-[100%]

              transition-all duration-1000
            "
          />

          <Eye
            size={16}
            className="relative z-10"
          />

          <span className="relative z-10">
            View Report
          </span>
        </button>

        {/* DOWNLOAD */}
        <button
          className="
            flex-1

            flex
            items-center
            justify-center

            gap-2.5

            px-5
            py-4

            rounded-[22px]

            bg-white/40
            backdrop-blur-xl

            border border-black/5

            text-slate-700
            font-bold

            transition-all duration-300

            hover:bg-white/60
            hover:text-red-800
          "
        >

          <Download size={16} />

          <span>
            Download
          </span>
        </button>
      </div>
    </div>
  );
}

export default ReportCard;